timeToWait:         0.5
tolerance:          0.1
maxSteps:           1000
topicName:          /ptu_driver/state_cmd
commandTopicName:   /ptu_driver/ptu_state
serviceValidation:  /ptu_driver/validation_service
serviceAlive:       /ptu_driver/alive_service
margin:             0.01

